name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
        imageName:
          description: 'Image Name' 
          required: true
        imageVersion:
          description: 'Image version' 
          required: true       

env: 
  DOCKER_REGISTRY: harbor-tls.af-klm.com

jobs:
  set-dockerFileDir:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.get-directories.outputs.directories }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get directories
        id: get-directories
        run: |
          find . -type d -printf "%P\n" > directories.txt
          
      - name: Select Docker directory
        id: select-directory
        run: |
          DIRECTORIES=$(cat directories.txt)
          OPTIONS=($DIRECTORIES)
          echo "::set-output name=selectedDirectory::${OPTIONS[${{ github.event.inputs.dockerFileDir }}]}"   

  build:
    runs-on: ubuntu-latest
    needs: set-dockerFileDir

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if directory exists
      id: checkDirectory
      run: |
        if [ -d ${{ github.event.inputs.dockerFileDir }} ]; then
          echo "${{ github.event.inputs.dockerFileDir }} exists"
        else
          echo "${{ github.event.inputs.dockerFileDir }} does not exist"
          exit 1
        fi
