name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
        dockerFileDir:
          description: 'Docker File Directory'     
          required: true
        imageName:
          description: 'Image Name' 
          required: true
        imageTag:
          description: 'Image tag' 
          required: true
        imageVersion:
          description: 'Image version' 
          required: true       


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - run: |
        echo "docker file  diretory : ${{ github.event.inputs.dockerFileDir }}"
        echo "image name : ${{ github.event.inputs.imageName }}" 
        echo "image tag : ${{ github.event.inputs.imageTag }}"
        echo "image version : ${{ github.event.inputs.imageVersion }}" 
        dockerFile_dir="${{ github.event.inputs.dockerFileDir }}" imageName="${{ github.event.inputs.imageName }}" imageTag="${{ github.event.inputs.imageTag }}" imageVersion="${{ github.event.inputs.imageVersion }}" ./ci/build_docker_images_github.sh
      shell: bash