name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
        imageName:
          description: 'Image Name' 
          required: true
          type: choice
          options:
          - image1/test
          - image2/test
          - image3/test
          - image0/test

env: 
  DOCKER_REGISTRY: harbor-tls.af-klm.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read map file and extract value
      id: extract-value
      run: |
        # Read the map file and extract the value using jq
        value=$(cat map.json | jq --raw-output .${{ github.event.inputs.imageName }})
        echo "::set-output name=value::$value"
   
    - name: Use the retrieved value
      run: |
        echo "Retrieved value: ${{ steps.extract-value.outputs.value }}"
