name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
        dockerFileDir:
          description: 'Docker File Directory'     
          required: true
        imageName:
          description: 'Image Name' 
          required: true
        imageVersion:
          description: 'Image version' 
          required: true       

env: 
  DOCKER_REGISTRY: harbor-tls.af-klm.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if directory exists
      id: checkDirectory
      run: |
        if [ -d ${{ github.event.inputs.dockerFileDir }} ]; then
          echo "${{ github.event.inputs.dockerFileDir }} exists"
        else
          echo "${{ github.event.inputs.dockerFileDir }} does not exist"
          exit 1
        fi

    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: $DOCKER_REGISTRY
        username: ${{ secrets.HARBOR_TLS_HOST }}
        password: ${{ secrets.HARBOR_TLS_PASSWORD }}
      id: login

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ github.event.inputs.dockerFileDir }}
        push: true
        tags: $DOCKER_REGISTRY/${{ github.event.inputs.imageName }}:${{ github.event.inputs.imageVersion }}-${{ github.run_number }}

    - name: Docker logout
      uses: docker/login-action@v2
      with: 
        logout: true
      if: steps.buildImage.login == 'success'
